version: '2'
services:
  web:
    container_name: "plex-server"
    image: "linuxserver/plex"
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
     - /home/christopher/stockage1/film/HD:/data/movies
    environment:
      - VERSION=latest
      - ALLOWED_NETWORKS=192.168.1.0/24,172.16.0.0/16
