version: '2'
services:
  web:
    container_name: "plex-server"
    image: "linuxserver/plex"
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "5353:5353/udp"
      - "1900:1900/udp"
    volumes:
     - /home/christopher/stockage1/film/HD:/data/movies
    environment:
      - VERSION=latest